//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeribanEFatura
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VeribanServiceFault
    {
        
        private string faultCodeField;
        
        private string faultDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FaultCode
        {
            get
            {
                return this.faultCodeField;
            }
            set
            {
                this.faultCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string FaultDescription
        {
            get
            {
                return this.faultDescriptionField;
            }
            set
            {
                this.faultDescriptionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VeribanEFatura.IIntegrationService")]
    public interface IIntegrationService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="Login", ReplyAction="Login")]
        [System.ServiceModel.FaultContractAttribute(typeof(VeribanEFatura.VeribanServiceFault), Action="Login", Name="VeribanServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> LoginAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="Logout", ReplyAction="Logout")]
        [System.ServiceModel.FaultContractAttribute(typeof(VeribanEFatura.VeribanServiceFault), Action="Logout", Name="VeribanServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task LogoutAsync(string sessionCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="TransferSalesInvoiceFile", ReplyAction="TransferSalesInvoiceFile")]
        [System.ServiceModel.FaultContractAttribute(typeof(VeribanEFatura.VeribanServiceFault), Action="TransferSalesInvoiceFile", Name="VeribanServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VeribanEFatura.TransferResult> TransferSalesInvoiceFileAsync(string sessionCode, VeribanEFatura.EInvoiceTransferFile transferFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="TransferSalesInvoiceFileWithIntegrationCode", ReplyAction="TransferSalesInvoiceFileWithIntegrationCode")]
        [System.ServiceModel.FaultContractAttribute(typeof(VeribanEFatura.VeribanServiceFault), Action="TransferSalesInvoiceFileWithIntegrationCode", Name="VeribanServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VeribanEFatura.TransferResult> TransferSalesInvoiceFileWithIntegrationCodeAsync(string sessionCode, VeribanEFatura.EInvoiceTransferFile transferFile, string uniqueIntegrationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="TransferPurchaseInvoiceAnswerFile", ReplyAction="TransferPurchaseInvoiceAnswerFile")]
        [System.ServiceModel.FaultContractAttribute(typeof(VeribanEFatura.VeribanServiceFault), Action="TransferPurchaseInvoiceAnswerFile", Name="VeribanServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VeribanEFatura.TransferResult> TransferPurchaseInvoiceAnswerFileAsync(string sessionCode, VeribanEFatura.EInvoiceTransferFile transferFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="TransferPurchaseInvoiceAnswerFileWithIntegrationCode", ReplyAction="TransferPurchaseInvoiceAnswerFileWithIntegrationCode")]
        [System.ServiceModel.FaultContractAttribute(typeof(VeribanEFatura.VeribanServiceFault), Action="TransferPurchaseInvoiceAnswerFileWithIntegrationCode", Name="VeribanServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VeribanEFatura.TransferResult> TransferPurchaseInvoiceAnswerFileWithIntegrationCodeAsync(string sessionCode, VeribanEFatura.EInvoiceTransferFile transferFile, string uniqueIntegrationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetTransferSalesInvoiceFileStatus", ReplyAction="GetTransferSalesInvoiceFileStatus")]
        [System.ServiceModel.FaultContractAttribute(typeof(VeribanEFatura.VeribanServiceFault), Action="GetTransferSalesInvoiceFileStatus", Name="VeribanServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VeribanEFatura.TransferQueryResult> GetTransferSalesInvoiceFileStatusAsync(string sessionCode, string transferFileUniqueId);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetTransferSalesInvoiceFileStatusWithIntegrationCode", ReplyAction="GetTransferSalesInvoiceFileStatusWithIntegrationCode")]
        [System.ServiceModel.FaultContractAttribute(typeof(VeribanEFatura.VeribanServiceFault), Action="GetTransferSalesInvoiceFileStatusWithIntegrationCode", Name="VeribanServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VeribanEFatura.TransferQueryResult> GetTransferSalesInvoiceFileStatusWithIntegrationCodeAsync(string sessionCode, string uniqueIntegrationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetTransferPurchaseInvoiceAnswerFileStatus", ReplyAction="GetTransferPurchaseInvoiceAnswerFileStatus")]
        [System.ServiceModel.FaultContractAttribute(typeof(VeribanEFatura.VeribanServiceFault), Action="GetTransferPurchaseInvoiceAnswerFileStatus", Name="VeribanServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VeribanEFatura.TransferQueryResult> GetTransferPurchaseInvoiceAnswerFileStatusAsync(string sessionCode, string transferFileUniqueId);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetTransferPurchaseInvoiceAnswerFileStatusWithIntegrationCode", ReplyAction="GetTransferPurchaseInvoiceAnswerFileStatusWithIntegrationCode")]
        [System.ServiceModel.FaultContractAttribute(typeof(VeribanEFatura.VeribanServiceFault), Action="GetTransferPurchaseInvoiceAnswerFileStatusWithIntegrationCode", Name="VeribanServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VeribanEFatura.TransferQueryResult> GetTransferPurchaseInvoiceAnswerFileStatusWithIntegrationCodeAsync(string sessionCode, string uniqueIntegrationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetSalesInvoiceStatusWithInvoiceUUID", ReplyAction="GetSalesInvoiceStatusWithInvoiceUUID")]
        [System.ServiceModel.FaultContractAttribute(typeof(VeribanEFatura.VeribanServiceFault), Action="GetSalesInvoiceStatusWithInvoiceUUID", Name="VeribanServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VeribanEFatura.EInvoiceSalesQueryResult> GetSalesInvoiceStatusWithInvoiceUUIDAsync(string sessionCode, string invoiceUUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetSalesInvoiceStatusWithInvoiceNumber", ReplyAction="GetSalesInvoiceStatusWithInvoiceNumber")]
        [System.ServiceModel.FaultContractAttribute(typeof(VeribanEFatura.VeribanServiceFault), Action="GetSalesInvoiceStatusWithInvoiceNumber", Name="VeribanServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VeribanEFatura.EInvoiceSalesQueryResult> GetSalesInvoiceStatusWithInvoiceNumberAsync(string sessionCode, string invoiceNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetSalesInvoiceStatusWithIntegrationCode", ReplyAction="GetSalesInvoiceStatusWithIntegrationCode")]
        [System.ServiceModel.FaultContractAttribute(typeof(VeribanEFatura.VeribanServiceFault), Action="GetSalesInvoiceStatusWithIntegrationCode", Name="VeribanServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VeribanEFatura.EInvoiceSalesQueryResult> GetSalesInvoiceStatusWithIntegrationCodeAsync(string sessionCode, string uniqueIntegrationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetPurchaseInvoiceStatusWithInvoiceUUID", ReplyAction="GetPurchaseInvoiceStatusWithInvoiceUUID")]
        [System.ServiceModel.FaultContractAttribute(typeof(VeribanEFatura.VeribanServiceFault), Action="GetPurchaseInvoiceStatusWithInvoiceUUID", Name="VeribanServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VeribanEFatura.EInvoicePurchaseQueryResult> GetPurchaseInvoiceStatusWithInvoiceUUIDAsync(string sessionCode, string invoiceUUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetPurchaseInvoiceStatusWithInvoiceNumber", ReplyAction="GetPurchaseInvoiceStatusWithInvoiceNumber")]
        [System.ServiceModel.FaultContractAttribute(typeof(VeribanEFatura.VeribanServiceFault), Action="GetPurchaseInvoiceStatusWithInvoiceNumber", Name="VeribanServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VeribanEFatura.EInvoicePurchaseQueryResult> GetPurchaseInvoiceStatusWithInvoiceNumberAsync(string sessionCode, string invoiceNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetCustomerAliasListWithRegisterNumber", ReplyAction="GetCustomerAliasListWithRegisterNumber")]
        [System.ServiceModel.FaultContractAttribute(typeof(VeribanEFatura.VeribanServiceFault), Action="GetCustomerAliasListWithRegisterNumber", Name="VeribanServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VeribanEFatura.CustomerData[]> GetCustomerAliasListWithRegisterNumberAsync(string sessionCode, string customerRegisterNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetSalesInvoiceUUIDList", ReplyAction="GetSalesInvoiceUUIDList")]
        [System.ServiceModel.FaultContractAttribute(typeof(VeribanEFatura.VeribanServiceFault), Action="GetSalesInvoiceUUIDList", Name="VeribanServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string[]> GetSalesInvoiceUUIDListAsync(string sessionCode, System.DateTime startDate, System.DateTime endDate, string customerRegisterNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetPurchaseInvoiceUUIDList", ReplyAction="GetPurchaseInvoiceUUIDList")]
        [System.ServiceModel.FaultContractAttribute(typeof(VeribanEFatura.VeribanServiceFault), Action="GetPurchaseInvoiceUUIDList", Name="VeribanServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string[]> GetPurchaseInvoiceUUIDListAsync(string sessionCode, System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetUnTransferredPurchaseInvoiceUUIDList", ReplyAction="GetUnTransferredPurchaseInvoiceUUIDList")]
        [System.ServiceModel.FaultContractAttribute(typeof(VeribanEFatura.VeribanServiceFault), Action="GetUnTransferredPurchaseInvoiceUUIDList", Name="VeribanServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string[]> GetUnTransferredPurchaseInvoiceUUIDListAsync(string sessionCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="SetUnTransferredPurchaseInvoiceDone", ReplyAction="SetUnTransferredPurchaseInvoiceDone")]
        [System.ServiceModel.FaultContractAttribute(typeof(VeribanEFatura.VeribanServiceFault), Action="SetUnTransferredPurchaseInvoiceDone", Name="VeribanServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> SetUnTransferredPurchaseInvoiceDoneAsync(string sessionCode, string invoiceUUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetWaitAnswerPurchaseInvoiceUUIDList", ReplyAction="GetWaitAnswerPurchaseInvoiceUUIDList")]
        [System.ServiceModel.FaultContractAttribute(typeof(VeribanEFatura.VeribanServiceFault), Action="GetWaitAnswerPurchaseInvoiceUUIDList", Name="VeribanServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string[]> GetWaitAnswerPurchaseInvoiceUUIDListAsync(string sessionCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="SetPurchaseInvoiceAnswerWithInvoiceUUID", ReplyAction="SetPurchaseInvoiceAnswerWithInvoiceUUID")]
        [System.ServiceModel.FaultContractAttribute(typeof(VeribanEFatura.VeribanServiceFault), Action="SetPurchaseInvoiceAnswerWithInvoiceUUID", Name="VeribanServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VeribanEFatura.SetPurchaseInvoiceAnswerWithInvoiceUUIDResponse> SetPurchaseInvoiceAnswerWithInvoiceUUIDAsync(VeribanEFatura.SetPurchaseInvoiceAnswerWithInvoiceUUIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SetPurchaseInvoiceAnswerWithInvoiceNumber", ReplyAction="SetPurchaseInvoiceAnswerWithInvoiceNumber")]
        [System.ServiceModel.FaultContractAttribute(typeof(VeribanEFatura.VeribanServiceFault), Action="SetPurchaseInvoiceAnswerWithInvoiceNumber", Name="VeribanServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VeribanEFatura.SetPurchaseInvoiceAnswerWithInvoiceNumberResponse> SetPurchaseInvoiceAnswerWithInvoiceNumberAsync(VeribanEFatura.SetPurchaseInvoiceAnswerWithInvoiceNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DownloadSalesInvoiceWithInvoiceUUID", ReplyAction="DownloadSalesInvoiceWithInvoiceUUID")]
        [System.ServiceModel.FaultContractAttribute(typeof(VeribanEFatura.VeribanServiceFault), Action="DownloadSalesInvoiceWithInvoiceUUID", Name="VeribanServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VeribanEFatura.DownloadResult> DownloadSalesInvoiceWithInvoiceUUIDAsync(string sessionCode, VeribanEFatura.DownloadDocumentDataTypes downloadDataType, string invoiceUUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="DownloadSalesInvoiceWithInvoiceNumber", ReplyAction="DownloadSalesInvoiceWithInvoiceNumber")]
        [System.ServiceModel.FaultContractAttribute(typeof(VeribanEFatura.VeribanServiceFault), Action="DownloadSalesInvoiceWithInvoiceNumber", Name="VeribanServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VeribanEFatura.DownloadResult> DownloadSalesInvoiceWithInvoiceNumberAsync(string sessionCode, VeribanEFatura.DownloadDocumentDataTypes downloadDataType, string invoiceNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DownloadSalesInvoiceWithIntegrationCode", ReplyAction="DownloadSalesInvoiceWithIntegrationCode")]
        [System.ServiceModel.FaultContractAttribute(typeof(VeribanEFatura.VeribanServiceFault), Action="DownloadSalesInvoiceWithIntegrationCode", Name="VeribanServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VeribanEFatura.DownloadResult> DownloadSalesInvoiceWithIntegrationCodeAsync(string sessionCode, VeribanEFatura.DownloadDocumentDataTypes downloadDataType, string uniqueIntegrationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="DownloadPurchaseInvoiceWithInvoiceUUID", ReplyAction="DownloadPurchaseInvoiceWithInvoiceUUID")]
        [System.ServiceModel.FaultContractAttribute(typeof(VeribanEFatura.VeribanServiceFault), Action="DownloadPurchaseInvoiceWithInvoiceUUID", Name="VeribanServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VeribanEFatura.DownloadResult> DownloadPurchaseInvoiceWithInvoiceUUIDAsync(string sessionCode, VeribanEFatura.DownloadDocumentDataTypes downloadDataType, string invoiceUUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="DownloadPurchaseInvoiceWithInvoiceNumber", ReplyAction="DownloadPurchaseInvoiceWithInvoiceNumber")]
        [System.ServiceModel.FaultContractAttribute(typeof(VeribanEFatura.VeribanServiceFault), Action="DownloadPurchaseInvoiceWithInvoiceNumber", Name="VeribanServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VeribanEFatura.DownloadResult> DownloadPurchaseInvoiceWithInvoiceNumberAsync(string sessionCode, VeribanEFatura.DownloadDocumentDataTypes downloadDataType, string invoiceNumber);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EInvoiceTransferFile : TransferFile
    {
        
        private string customerAliasField;
        
        private bool isDirectSendField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CustomerAlias
        {
            get
            {
                return this.customerAliasField;
            }
            set
            {
                this.customerAliasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool IsDirectSend
        {
            get
            {
                return this.isDirectSendField;
            }
            set
            {
                this.isDirectSendField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EInvoiceTransferFile))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TransferFile
    {
        
        private TransferDocumentDataTypes fileDataTypeField;
        
        private string fileNameWithExtensionField;
        
        private byte[] binaryDataField;
        
        private string binaryDataHashField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TransferDocumentDataTypes FileDataType
        {
            get
            {
                return this.fileDataTypeField;
            }
            set
            {
                this.fileDataTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FileNameWithExtension
        {
            get
            {
                return this.fileNameWithExtensionField;
            }
            set
            {
                this.fileNameWithExtensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] BinaryData
        {
            get
            {
                return this.binaryDataField;
            }
            set
            {
                this.binaryDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BinaryDataHash
        {
            get
            {
                return this.binaryDataHashField;
            }
            set
            {
                this.binaryDataHashField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum TransferDocumentDataTypes
    {
        
        /// <remarks/>
        XML_INZIP,
        
        /// <remarks/>
        TXT_INZIP,
        
        /// <remarks/>
        CSV_INZIP,
        
        /// <remarks/>
        XLS_INZIP,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TransferResult : OperationResult
    {
        
        private string transferFileUniqueIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TransferFileUniqueId
        {
            get
            {
                return this.transferFileUniqueIdField;
            }
            set
            {
                this.transferFileUniqueIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransferResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OperationResult
    {
        
        private bool operationCompletedField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool OperationCompleted
        {
            get
            {
                return this.operationCompletedField;
            }
            set
            {
                this.operationCompletedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TransferQueryResult : DocumentQueryResult
    {
        
        private System.Nullable<System.DateTime> insertTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<System.DateTime> InsertTime
        {
            get
            {
                return this.insertTimeField;
            }
            set
            {
                this.insertTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EInvoicePurchaseQueryResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EInvoiceSalesQueryResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransferQueryResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DocumentQueryResult
    {
        
        private int stateCodeField;
        
        private string stateNameField;
        
        private string stateDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int StateCode
        {
            get
            {
                return this.stateCodeField;
            }
            set
            {
                this.stateCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StateName
        {
            get
            {
                return this.stateNameField;
            }
            set
            {
                this.stateNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StateDescription
        {
            get
            {
                return this.stateDescriptionField;
            }
            set
            {
                this.stateDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EInvoicePurchaseQueryResult : DocumentQueryResult
    {
        
        private byte answerStateCodeField;
        
        private string answerStateNameField;
        
        private string answerStateDescriptionField;
        
        private byte answerTypeCodeField;
        
        private string answerTypeNameField;
        
        private string answerTypeDescriptionField;
        
        private string envelopeIdentifierField;
        
        private int envelopeGIBCodeField;
        
        private string envelopeGIBStateNameField;
        
        private string envelopeCreationTimeField;
        
        private string answerEnvelopeIdentifierField;
        
        private int answerEnvelopeGIBCodeField;
        
        private string answerEnvelopeGIBStateNameField;
        
        private string answerEnvelopeCreationTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public byte AnswerStateCode
        {
            get
            {
                return this.answerStateCodeField;
            }
            set
            {
                this.answerStateCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AnswerStateName
        {
            get
            {
                return this.answerStateNameField;
            }
            set
            {
                this.answerStateNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AnswerStateDescription
        {
            get
            {
                return this.answerStateDescriptionField;
            }
            set
            {
                this.answerStateDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public byte AnswerTypeCode
        {
            get
            {
                return this.answerTypeCodeField;
            }
            set
            {
                this.answerTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AnswerTypeName
        {
            get
            {
                return this.answerTypeNameField;
            }
            set
            {
                this.answerTypeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string AnswerTypeDescription
        {
            get
            {
                return this.answerTypeDescriptionField;
            }
            set
            {
                this.answerTypeDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string EnvelopeIdentifier
        {
            get
            {
                return this.envelopeIdentifierField;
            }
            set
            {
                this.envelopeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int EnvelopeGIBCode
        {
            get
            {
                return this.envelopeGIBCodeField;
            }
            set
            {
                this.envelopeGIBCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string EnvelopeGIBStateName
        {
            get
            {
                return this.envelopeGIBStateNameField;
            }
            set
            {
                this.envelopeGIBStateNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string EnvelopeCreationTime
        {
            get
            {
                return this.envelopeCreationTimeField;
            }
            set
            {
                this.envelopeCreationTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string AnswerEnvelopeIdentifier
        {
            get
            {
                return this.answerEnvelopeIdentifierField;
            }
            set
            {
                this.answerEnvelopeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int AnswerEnvelopeGIBCode
        {
            get
            {
                return this.answerEnvelopeGIBCodeField;
            }
            set
            {
                this.answerEnvelopeGIBCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string AnswerEnvelopeGIBStateName
        {
            get
            {
                return this.answerEnvelopeGIBStateNameField;
            }
            set
            {
                this.answerEnvelopeGIBStateNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string AnswerEnvelopeCreationTime
        {
            get
            {
                return this.answerEnvelopeCreationTimeField;
            }
            set
            {
                this.answerEnvelopeCreationTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EInvoiceSalesQueryResult : DocumentQueryResult
    {
        
        private byte answerStateCodeField;
        
        private string answerStateNameField;
        
        private string answerStateDescriptionField;
        
        private byte answerTypeCodeField;
        
        private string answerTypeNameField;
        
        private string answerTypeDescriptionField;
        
        private string envelopeIdentifierField;
        
        private int envelopeGIBCodeField;
        
        private string envelopeGIBStateNameField;
        
        private string envelopeCreationTimeField;
        
        private string answerEnvelopeIdentifierField;
        
        private int answerEnvelopeGIBCodeField;
        
        private string answerEnvelopeGIBStateNameField;
        
        private string answerEnvelopeCreationTimeField;
        
        private string gtbReferenceNumberField;
        
        private string gtbGcbTescilNoField;
        
        private string gtbFiiliIhracatTarihiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public byte AnswerStateCode
        {
            get
            {
                return this.answerStateCodeField;
            }
            set
            {
                this.answerStateCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AnswerStateName
        {
            get
            {
                return this.answerStateNameField;
            }
            set
            {
                this.answerStateNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AnswerStateDescription
        {
            get
            {
                return this.answerStateDescriptionField;
            }
            set
            {
                this.answerStateDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public byte AnswerTypeCode
        {
            get
            {
                return this.answerTypeCodeField;
            }
            set
            {
                this.answerTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AnswerTypeName
        {
            get
            {
                return this.answerTypeNameField;
            }
            set
            {
                this.answerTypeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string AnswerTypeDescription
        {
            get
            {
                return this.answerTypeDescriptionField;
            }
            set
            {
                this.answerTypeDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string EnvelopeIdentifier
        {
            get
            {
                return this.envelopeIdentifierField;
            }
            set
            {
                this.envelopeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int EnvelopeGIBCode
        {
            get
            {
                return this.envelopeGIBCodeField;
            }
            set
            {
                this.envelopeGIBCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string EnvelopeGIBStateName
        {
            get
            {
                return this.envelopeGIBStateNameField;
            }
            set
            {
                this.envelopeGIBStateNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string EnvelopeCreationTime
        {
            get
            {
                return this.envelopeCreationTimeField;
            }
            set
            {
                this.envelopeCreationTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string AnswerEnvelopeIdentifier
        {
            get
            {
                return this.answerEnvelopeIdentifierField;
            }
            set
            {
                this.answerEnvelopeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int AnswerEnvelopeGIBCode
        {
            get
            {
                return this.answerEnvelopeGIBCodeField;
            }
            set
            {
                this.answerEnvelopeGIBCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string AnswerEnvelopeGIBStateName
        {
            get
            {
                return this.answerEnvelopeGIBStateNameField;
            }
            set
            {
                this.answerEnvelopeGIBStateNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string AnswerEnvelopeCreationTime
        {
            get
            {
                return this.answerEnvelopeCreationTimeField;
            }
            set
            {
                this.answerEnvelopeCreationTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string GtbReferenceNumber
        {
            get
            {
                return this.gtbReferenceNumberField;
            }
            set
            {
                this.gtbReferenceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string GtbGcbTescilNo
        {
            get
            {
                return this.gtbGcbTescilNoField;
            }
            set
            {
                this.gtbGcbTescilNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string GtbFiiliIhracatTarihi
        {
            get
            {
                return this.gtbFiiliIhracatTarihiField;
            }
            set
            {
                this.gtbFiiliIhracatTarihiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomerData
    {
        
        private string identifierNumberField;
        
        private string aliasField;
        
        private string titleField;
        
        private string typeField;
        
        private System.DateTime registerTimeField;
        
        private System.Nullable<System.DateTime> aliasCreationTimeField;
        
        private string documentTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IdentifierNumber
        {
            get
            {
                return this.identifierNumberField;
            }
            set
            {
                this.identifierNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Alias
        {
            get
            {
                return this.aliasField;
            }
            set
            {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime RegisterTime
        {
            get
            {
                return this.registerTimeField;
            }
            set
            {
                this.registerTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> AliasCreationTime
        {
            get
            {
                return this.aliasCreationTimeField;
            }
            set
            {
                this.aliasCreationTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DocumentType
        {
            get
            {
                return this.documentTypeField;
            }
            set
            {
                this.documentTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetPurchaseInvoiceAnswerWithInvoiceUUID", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetPurchaseInvoiceAnswerWithInvoiceUUIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sessionCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string answerType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> answerTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string answerNote;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public bool isDirectSend;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string invoiceUUID;
        
        public SetPurchaseInvoiceAnswerWithInvoiceUUIDRequest()
        {
        }
        
        public SetPurchaseInvoiceAnswerWithInvoiceUUIDRequest(string sessionCode, string answerType, System.Nullable<System.DateTime> answerTime, string answerNote, bool isDirectSend, string invoiceUUID)
        {
            this.sessionCode = sessionCode;
            this.answerType = answerType;
            this.answerTime = answerTime;
            this.answerNote = answerNote;
            this.isDirectSend = isDirectSend;
            this.invoiceUUID = invoiceUUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetPurchaseInvoiceAnswerWithInvoiceUUIDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetPurchaseInvoiceAnswerWithInvoiceUUIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public VeribanEFatura.OperationResult SetPurchaseInvoiceAnswerWithInvoiceUUIDResult;
        
        public SetPurchaseInvoiceAnswerWithInvoiceUUIDResponse()
        {
        }
        
        public SetPurchaseInvoiceAnswerWithInvoiceUUIDResponse(VeribanEFatura.OperationResult SetPurchaseInvoiceAnswerWithInvoiceUUIDResult)
        {
            this.SetPurchaseInvoiceAnswerWithInvoiceUUIDResult = SetPurchaseInvoiceAnswerWithInvoiceUUIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetPurchaseInvoiceAnswerWithInvoiceNumber", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetPurchaseInvoiceAnswerWithInvoiceNumberRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sessionCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string answerType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> answerTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string answerNote;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public bool isDirectSend;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string invoiceNumber;
        
        public SetPurchaseInvoiceAnswerWithInvoiceNumberRequest()
        {
        }
        
        public SetPurchaseInvoiceAnswerWithInvoiceNumberRequest(string sessionCode, string answerType, System.Nullable<System.DateTime> answerTime, string answerNote, bool isDirectSend, string invoiceNumber)
        {
            this.sessionCode = sessionCode;
            this.answerType = answerType;
            this.answerTime = answerTime;
            this.answerNote = answerNote;
            this.isDirectSend = isDirectSend;
            this.invoiceNumber = invoiceNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetPurchaseInvoiceAnswerWithInvoiceNumberResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetPurchaseInvoiceAnswerWithInvoiceNumberResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public VeribanEFatura.OperationResult SetPurchaseInvoiceAnswerWithInvoiceNumberResult;
        
        public SetPurchaseInvoiceAnswerWithInvoiceNumberResponse()
        {
        }
        
        public SetPurchaseInvoiceAnswerWithInvoiceNumberResponse(VeribanEFatura.OperationResult SetPurchaseInvoiceAnswerWithInvoiceNumberResult)
        {
            this.SetPurchaseInvoiceAnswerWithInvoiceNumberResult = SetPurchaseInvoiceAnswerWithInvoiceNumberResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum DownloadDocumentDataTypes
    {
        
        /// <remarks/>
        XML_INZIP,
        
        /// <remarks/>
        HTML_INZIP,
        
        /// <remarks/>
        IMAGE_INZIP,
        
        /// <remarks/>
        PDF_INZIP,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DownloadResult
    {
        
        private string referenceCodeField;
        
        private bool downloadFileReadyField;
        
        private string downloadDescriptionField;
        
        private DownloadFile downloadFileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ReferenceCode
        {
            get
            {
                return this.referenceCodeField;
            }
            set
            {
                this.referenceCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool DownloadFileReady
        {
            get
            {
                return this.downloadFileReadyField;
            }
            set
            {
                this.downloadFileReadyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DownloadDescription
        {
            get
            {
                return this.downloadDescriptionField;
            }
            set
            {
                this.downloadDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public DownloadFile DownloadFile
        {
            get
            {
                return this.downloadFileField;
            }
            set
            {
                this.downloadFileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DownloadFile
    {
        
        private string fileNameField;
        
        private string fileExtensionField;
        
        private string fileHashField;
        
        private byte[] fileDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FileExtension
        {
            get
            {
                return this.fileExtensionField;
            }
            set
            {
                this.fileExtensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FileHash
        {
            get
            {
                return this.fileHashField;
            }
            set
            {
                this.fileHashField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=3)]
        public byte[] FileData
        {
            get
            {
                return this.fileDataField;
            }
            set
            {
                this.fileDataField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IIntegrationServiceChannel : VeribanEFatura.IIntegrationService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class IntegrationServiceClient : System.ServiceModel.ClientBase<VeribanEFatura.IIntegrationService>, VeribanEFatura.IIntegrationService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public IntegrationServiceClient() : 
                base(IntegrationServiceClient.GetDefaultBinding(), IntegrationServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IIntegrationService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IntegrationServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(IntegrationServiceClient.GetBindingForEndpoint(endpointConfiguration), IntegrationServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IntegrationServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(IntegrationServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IntegrationServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(IntegrationServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IntegrationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(string userName, string password)
        {
            return base.Channel.LoginAsync(userName, password);
        }
        
        public System.Threading.Tasks.Task LogoutAsync(string sessionCode)
        {
            return base.Channel.LogoutAsync(sessionCode);
        }
        
        public System.Threading.Tasks.Task<VeribanEFatura.TransferResult> TransferSalesInvoiceFileAsync(string sessionCode, VeribanEFatura.EInvoiceTransferFile transferFile)
        {
            return base.Channel.TransferSalesInvoiceFileAsync(sessionCode, transferFile);
        }
        
        public System.Threading.Tasks.Task<VeribanEFatura.TransferResult> TransferSalesInvoiceFileWithIntegrationCodeAsync(string sessionCode, VeribanEFatura.EInvoiceTransferFile transferFile, string uniqueIntegrationCode)
        {
            return base.Channel.TransferSalesInvoiceFileWithIntegrationCodeAsync(sessionCode, transferFile, uniqueIntegrationCode);
        }
        
        public System.Threading.Tasks.Task<VeribanEFatura.TransferResult> TransferPurchaseInvoiceAnswerFileAsync(string sessionCode, VeribanEFatura.EInvoiceTransferFile transferFile)
        {
            return base.Channel.TransferPurchaseInvoiceAnswerFileAsync(sessionCode, transferFile);
        }
        
        public System.Threading.Tasks.Task<VeribanEFatura.TransferResult> TransferPurchaseInvoiceAnswerFileWithIntegrationCodeAsync(string sessionCode, VeribanEFatura.EInvoiceTransferFile transferFile, string uniqueIntegrationCode)
        {
            return base.Channel.TransferPurchaseInvoiceAnswerFileWithIntegrationCodeAsync(sessionCode, transferFile, uniqueIntegrationCode);
        }
        
        public System.Threading.Tasks.Task<VeribanEFatura.TransferQueryResult> GetTransferSalesInvoiceFileStatusAsync(string sessionCode, string transferFileUniqueId)
        {
            return base.Channel.GetTransferSalesInvoiceFileStatusAsync(sessionCode, transferFileUniqueId);
        }
        
        public System.Threading.Tasks.Task<VeribanEFatura.TransferQueryResult> GetTransferSalesInvoiceFileStatusWithIntegrationCodeAsync(string sessionCode, string uniqueIntegrationCode)
        {
            return base.Channel.GetTransferSalesInvoiceFileStatusWithIntegrationCodeAsync(sessionCode, uniqueIntegrationCode);
        }
        
        public System.Threading.Tasks.Task<VeribanEFatura.TransferQueryResult> GetTransferPurchaseInvoiceAnswerFileStatusAsync(string sessionCode, string transferFileUniqueId)
        {
            return base.Channel.GetTransferPurchaseInvoiceAnswerFileStatusAsync(sessionCode, transferFileUniqueId);
        }
        
        public System.Threading.Tasks.Task<VeribanEFatura.TransferQueryResult> GetTransferPurchaseInvoiceAnswerFileStatusWithIntegrationCodeAsync(string sessionCode, string uniqueIntegrationCode)
        {
            return base.Channel.GetTransferPurchaseInvoiceAnswerFileStatusWithIntegrationCodeAsync(sessionCode, uniqueIntegrationCode);
        }
        
        public System.Threading.Tasks.Task<VeribanEFatura.EInvoiceSalesQueryResult> GetSalesInvoiceStatusWithInvoiceUUIDAsync(string sessionCode, string invoiceUUID)
        {
            return base.Channel.GetSalesInvoiceStatusWithInvoiceUUIDAsync(sessionCode, invoiceUUID);
        }
        
        public System.Threading.Tasks.Task<VeribanEFatura.EInvoiceSalesQueryResult> GetSalesInvoiceStatusWithInvoiceNumberAsync(string sessionCode, string invoiceNumber)
        {
            return base.Channel.GetSalesInvoiceStatusWithInvoiceNumberAsync(sessionCode, invoiceNumber);
        }
        
        public System.Threading.Tasks.Task<VeribanEFatura.EInvoiceSalesQueryResult> GetSalesInvoiceStatusWithIntegrationCodeAsync(string sessionCode, string uniqueIntegrationCode)
        {
            return base.Channel.GetSalesInvoiceStatusWithIntegrationCodeAsync(sessionCode, uniqueIntegrationCode);
        }
        
        public System.Threading.Tasks.Task<VeribanEFatura.EInvoicePurchaseQueryResult> GetPurchaseInvoiceStatusWithInvoiceUUIDAsync(string sessionCode, string invoiceUUID)
        {
            return base.Channel.GetPurchaseInvoiceStatusWithInvoiceUUIDAsync(sessionCode, invoiceUUID);
        }
        
        public System.Threading.Tasks.Task<VeribanEFatura.EInvoicePurchaseQueryResult> GetPurchaseInvoiceStatusWithInvoiceNumberAsync(string sessionCode, string invoiceNumber)
        {
            return base.Channel.GetPurchaseInvoiceStatusWithInvoiceNumberAsync(sessionCode, invoiceNumber);
        }
        
        public System.Threading.Tasks.Task<VeribanEFatura.CustomerData[]> GetCustomerAliasListWithRegisterNumberAsync(string sessionCode, string customerRegisterNumber)
        {
            return base.Channel.GetCustomerAliasListWithRegisterNumberAsync(sessionCode, customerRegisterNumber);
        }
        
        public System.Threading.Tasks.Task<string[]> GetSalesInvoiceUUIDListAsync(string sessionCode, System.DateTime startDate, System.DateTime endDate, string customerRegisterNumber)
        {
            return base.Channel.GetSalesInvoiceUUIDListAsync(sessionCode, startDate, endDate, customerRegisterNumber);
        }
        
        public System.Threading.Tasks.Task<string[]> GetPurchaseInvoiceUUIDListAsync(string sessionCode, System.DateTime startDate, System.DateTime endDate)
        {
            return base.Channel.GetPurchaseInvoiceUUIDListAsync(sessionCode, startDate, endDate);
        }
        
        public System.Threading.Tasks.Task<string[]> GetUnTransferredPurchaseInvoiceUUIDListAsync(string sessionCode)
        {
            return base.Channel.GetUnTransferredPurchaseInvoiceUUIDListAsync(sessionCode);
        }
        
        public System.Threading.Tasks.Task<bool> SetUnTransferredPurchaseInvoiceDoneAsync(string sessionCode, string invoiceUUID)
        {
            return base.Channel.SetUnTransferredPurchaseInvoiceDoneAsync(sessionCode, invoiceUUID);
        }
        
        public System.Threading.Tasks.Task<string[]> GetWaitAnswerPurchaseInvoiceUUIDListAsync(string sessionCode)
        {
            return base.Channel.GetWaitAnswerPurchaseInvoiceUUIDListAsync(sessionCode);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VeribanEFatura.SetPurchaseInvoiceAnswerWithInvoiceUUIDResponse> VeribanEFatura.IIntegrationService.SetPurchaseInvoiceAnswerWithInvoiceUUIDAsync(VeribanEFatura.SetPurchaseInvoiceAnswerWithInvoiceUUIDRequest request)
        {
            return base.Channel.SetPurchaseInvoiceAnswerWithInvoiceUUIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<VeribanEFatura.SetPurchaseInvoiceAnswerWithInvoiceUUIDResponse> SetPurchaseInvoiceAnswerWithInvoiceUUIDAsync(string sessionCode, string answerType, System.Nullable<System.DateTime> answerTime, string answerNote, bool isDirectSend, string invoiceUUID)
        {
            VeribanEFatura.SetPurchaseInvoiceAnswerWithInvoiceUUIDRequest inValue = new VeribanEFatura.SetPurchaseInvoiceAnswerWithInvoiceUUIDRequest();
            inValue.sessionCode = sessionCode;
            inValue.answerType = answerType;
            inValue.answerTime = answerTime;
            inValue.answerNote = answerNote;
            inValue.isDirectSend = isDirectSend;
            inValue.invoiceUUID = invoiceUUID;
            return ((VeribanEFatura.IIntegrationService)(this)).SetPurchaseInvoiceAnswerWithInvoiceUUIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VeribanEFatura.SetPurchaseInvoiceAnswerWithInvoiceNumberResponse> VeribanEFatura.IIntegrationService.SetPurchaseInvoiceAnswerWithInvoiceNumberAsync(VeribanEFatura.SetPurchaseInvoiceAnswerWithInvoiceNumberRequest request)
        {
            return base.Channel.SetPurchaseInvoiceAnswerWithInvoiceNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<VeribanEFatura.SetPurchaseInvoiceAnswerWithInvoiceNumberResponse> SetPurchaseInvoiceAnswerWithInvoiceNumberAsync(string sessionCode, string answerType, System.Nullable<System.DateTime> answerTime, string answerNote, bool isDirectSend, string invoiceNumber)
        {
            VeribanEFatura.SetPurchaseInvoiceAnswerWithInvoiceNumberRequest inValue = new VeribanEFatura.SetPurchaseInvoiceAnswerWithInvoiceNumberRequest();
            inValue.sessionCode = sessionCode;
            inValue.answerType = answerType;
            inValue.answerTime = answerTime;
            inValue.answerNote = answerNote;
            inValue.isDirectSend = isDirectSend;
            inValue.invoiceNumber = invoiceNumber;
            return ((VeribanEFatura.IIntegrationService)(this)).SetPurchaseInvoiceAnswerWithInvoiceNumberAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<VeribanEFatura.DownloadResult> DownloadSalesInvoiceWithInvoiceUUIDAsync(string sessionCode, VeribanEFatura.DownloadDocumentDataTypes downloadDataType, string invoiceUUID)
        {
            return base.Channel.DownloadSalesInvoiceWithInvoiceUUIDAsync(sessionCode, downloadDataType, invoiceUUID);
        }
        
        public System.Threading.Tasks.Task<VeribanEFatura.DownloadResult> DownloadSalesInvoiceWithInvoiceNumberAsync(string sessionCode, VeribanEFatura.DownloadDocumentDataTypes downloadDataType, string invoiceNumber)
        {
            return base.Channel.DownloadSalesInvoiceWithInvoiceNumberAsync(sessionCode, downloadDataType, invoiceNumber);
        }
        
        public System.Threading.Tasks.Task<VeribanEFatura.DownloadResult> DownloadSalesInvoiceWithIntegrationCodeAsync(string sessionCode, VeribanEFatura.DownloadDocumentDataTypes downloadDataType, string uniqueIntegrationCode)
        {
            return base.Channel.DownloadSalesInvoiceWithIntegrationCodeAsync(sessionCode, downloadDataType, uniqueIntegrationCode);
        }
        
        public System.Threading.Tasks.Task<VeribanEFatura.DownloadResult> DownloadPurchaseInvoiceWithInvoiceUUIDAsync(string sessionCode, VeribanEFatura.DownloadDocumentDataTypes downloadDataType, string invoiceUUID)
        {
            return base.Channel.DownloadPurchaseInvoiceWithInvoiceUUIDAsync(sessionCode, downloadDataType, invoiceUUID);
        }
        
        public System.Threading.Tasks.Task<VeribanEFatura.DownloadResult> DownloadPurchaseInvoiceWithInvoiceNumberAsync(string sessionCode, VeribanEFatura.DownloadDocumentDataTypes downloadDataType, string invoiceNumber)
        {
            return base.Channel.DownloadPurchaseInvoiceWithInvoiceNumberAsync(sessionCode, downloadDataType, invoiceNumber);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public new  virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IIntegrationService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IIntegrationService))
            {
                return new System.ServiceModel.EndpointAddress("http://efaturatransfer.veriban.com.tr/IntegrationService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return IntegrationServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IIntegrationService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return IntegrationServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IIntegrationService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IIntegrationService,
        }
    }
}
